config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'

  get 'messages/index'

  get 'messages/new'

  ActiveAdmin.routes(self)
  resources :vacationplans
  resources :roomplans
  resources :carevents
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]
  # root 'welcome#index'

  get 'index' => 'welcome#index'
  get 'carevents/:id' => 'carevents#index'
  get 'roomplans/:id' => 'roomplans#index'
  get 'vacationplans/:id' => 'vacationplans#index'

  resources :messages do
    resources :comments
  end

  # root 'messages#index'
  # get 'welcome/index'

  # The priority is based upon order
  # of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller
  # actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/roomplan.rb
# Model fuer die Raumplanung
class Roomplan < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
  validates :usage, presence:  true
  validates_datetime :start_time, before: :end_time, after: :today
  validates_time :start_time, between: '8:00am'..'7:00pm'
  validates_time :end_time, between: '8:00am'..'7:00pm'
end

app/controllers/roomplans_controller.rb
# Der Controller wird fuer die Raumplanung benoetigt
class RoomplansController < ApplicationController
  before_action :set_roomplan, only: [:show, :edit, :update, :destroy]
  before_action :check_auth, only: [:edit, :update, :destroy]
  load_and_authorize_resource

  # GET /roomplans
  # GET /roomplans.json
  def index
    @roomplans = Roomplan.all
    @rooms = Room.all
  end

  # check authentification
  def check_auth
    if current_user.id != @roomplan.user_id
      if current_user.has_role?(:admin)
        # Admins duerfen loeschen
      else
        flash[:notice] = 'Sie können Einträge anderer Nutzer nicht ändern / löschen'
        redirect_to roomplan_path
      end
    end
  end

  # GET /roomplans/1
  # GET /roomplans/1.json
  def show
  end

  # GET /roomplans/new
  def new
    @roomplan = Roomplan.new
  end

  # GET /roomplans/1/edit
  def edit
  end

  # POST /roomplans
  # POST /roomplans.json
  def create
    @roomplan = Roomplan.new(roomplan_params)
    @roomplan.user_id = current_user.id

    respond_to do |format|
      if @roomplan.save
        format.html { redirect_to @roomplan, notice: 'Eintrag wurde erfolgreich erstellt.' }
        format.json { render :show, status: :created, location: @roomplan }
      else
        format.html { render :new }
        format.json { render json: @roomplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roomplans/1
  # PATCH/PUT /roomplans/1.json
  def update
    respond_to do |format|
      if @roomplan.update(roomplan_params)
        format.html { redirect_to @roomplan, notice: 'Eintrag wurde erfolgreich aktualisiert.' }
        format.json { render :show, status: :ok, location: @roomplan }
      else
        format.html { render :edit }
        format.json { render json: @roomplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roomplans/1
  # DELETE /roomplans/1.json
  def destroy
    @roomplan.destroy
    respond_to do |format|
      format.html { redirect_to roomplans_url, notice: 'Eintrag wurde erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_roomplan
    @roomplan = Roomplan.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def roomplan_params
    params.require(:roomplan).permit(:room_id, :usage, :start_time, :end_time)
  end
end

app/helpers/roomplans_helper.rb
# Leeres RoomplansHelper module
module RoomplansHelper
end

app/views/roomplans/_form.html.erb
<%= form_for(@roomplan) do |f| %>
  <% if @roomplan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roomplan.errors.count, "error") %> verhindert/verhindern die Speicherung des Eintrags:</h2>

      <ul>
      <% @roomplan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label 'Raum' %><br>
      <%= f.collection_select :room_id, Room.all, :id, :name %>
    </div>
  <div class="field">
    <%= f.label 'Benutzung' %><br>
    <%= f.text_field :usage %>
  </div>
  <div class="field">
    <%= f.label 'Start' %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label 'Ende' %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit value='Abschicken' %>
  </div>
<% end %>

app/views/roomplans/edit.html.erb
<h1>Raumbelegung editieren</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @roomplan %> |
<%= link_to 'Zurück', roomplans_path %>

app/views/roomplans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kalender zur Raumbelegung</h1>

<div id="button1"><h2><%= link_to 'Neue Raumbelegung', new_roomplan_path %></h2></div>

<br>
<br>

<%= month_calendar events: @roomplans do |date, roomplans| %>
    <b><%= date.strftime("%d.%m.%Y") %></b>

    <% roomplans.each do |roomplan| %>
        <div>
          <%= roomplan.user.first_name %> <%= roomplan.user.last_name %>
          <br>
          <%= link_to roomplan.room.name, roomplan %>
          <br>
          <%= roomplan.start_time.strftime("%H:%M") %> - <%= roomplan.end_time.strftime("%H:%M") %>
          <br>
          <%= link_to 'A', roomplan %> - <%= link_to 'E', edit_roomplan_path(roomplan) %> - <%= link_to 'L', roomplan, method: :delete, data: { confirm: 'Sind Sie sicher?' } %>
          <hr>
        </div>
    <% end %>
<% end %>
<p>
  Legende:<br>A -> Anzeigen, E -> Editieren, L -> Löschen
</p>


<h2>Insgesamt verfügbare Räume</h2>

<% @rooms.each do |room| %>
    <ul>
      <li><%= room.name %></li>
    </ul>

<% end %>

app/views/roomplans/new.html.erb
<h1>Neue Raumbelegung</h1>

<%= render 'form' %>

<%= link_to 'Zurück', roomplans_path %>

app/views/roomplans/show.html.erb
<p>
  <strong>Mitarbeiter:</strong>
  <%= @roomplan.user.first_name %> <%= @roomplan.user.last_name %>
</p>

<p>
  <strong>Raum:</strong>
  <%= @roomplan.room.name %>
</p>

<p>
  <strong>Benutzung:</strong>
  <%= @roomplan.usage %>
</p>

<p>
  <strong>Start:</strong>
  <%= @roomplan.start_time.strftime("%d.%m.%Y %H:%M") %>
</p>

<p>
  <strong>Ende:</strong>
  <%= @roomplan.end_time.strftime("%d.%m.%Y %H:%M") %>
</p>

<%= link_to 'Editieren', edit_roomplan_path(@roomplan) %> |
<%= link_to 'Zurück', roomplans_path %>