config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'

  get 'messages/index'

  get 'messages/new'

  ActiveAdmin.routes(self)
  resources :vacationplans
  resources :roomplans
  resources :carevents
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]
  # root 'welcome#index'

  get 'index' => 'welcome#index'
  get 'carevents/:id' => 'carevents#index'
  get 'roomplans/:id' => 'roomplans#index'
  get 'vacationplans/:id' => 'vacationplans#index'

  resources :messages do
    resources :comments
  end

  # root 'messages#index'
  # get 'welcome/index'

  # The priority is based upon order
  # of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller
  # actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/carevent.rb
# Model fuer die Autoplanung
class Carevent < ActiveRecord::Base
  belongs_to :car
  belongs_to :user
  validates :title, :description, presence:  true
  validates_datetime :start_time, before: :end_time, after: :today
end

app/controllers/carevents_controller.rb
# Der Controller wird fuer die Autoplanung benoetigt
class CareventsController < ApplicationController
  before_action :set_carevent, only: [:show, :edit, :update, :destroy]
  before_action :check_auth, only: [:edit, :update, :destroy]
  load_and_authorize_resource

  # public

  # GET /carevents
  # GET /carevents.json
  def index
    @carevents = Carevent.all
    @cars = Car.all
  end

  # check authentification
  def check_auth
    notice_check_auth = String.new('Sie können Einträge anderer Nutzer nicht ändern / löschen')
    if current_user.id != @carevent.user_id
      if current_user.has_role?(:admin)
        # Admins duerfen loeschen
      else
        flash[:notice] = notice_check_auth
        redirect_to carevent_path
      end
    end
  end

  # GET /carevents/1
  # GET /carevents/1.json
  def show
  end

  # GET /carevents/new
  def new
    @carevent = Carevent.new
  end

  # GET /carevents/1/edit
  def edit
  end

  # POST /carevents
  # POST /carevents.json
  def create
    notice_create = String.new('Eintrag wurde erfolgreich erstellt.')
    @carevent = Carevent.new(carevent_params)
    @carevent.user_id = current_user.id

    respond_to do |format|
      if @carevent.save
        format.html { redirect_to @carevent, notice: notice_create }
        format.json { render :show, status: :created, location: @carevent }
      else
        format.html { render :new }
        format.json { render json: @carevent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carevents/1
  # PATCH/PUT /carevents/1.json
  def update
    notice_update = String.new('Eintrag wurde erfolgreich aktualisiert.')
    respond_to do |format|
      if @carevent.update(carevent_params)
        format.html { redirect_to @carevent, notice: notice_update }
        format.json { render :show, status: :ok, location: @carevent }
      else
        format.html { render :edit }
        format.json { render json: @carevent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carevents/1
  # DELETE /carevents/1.json
  def destroy
    notice_destroy = String.new('Eintrag wurde erfolgreich gelöscht.')
    @carevent.destroy

    respond_to do |format|
      format.html { redirect_to carevents_url, notice: notice_destroy }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_carevent
    @carevent = Carevent.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def carevent_params
    params.require(:carevent).permit(:title,
                                     :description,
                                     :start_time,
                                     :end_time,
                                     :car_id)
  end
end

app/helpers/carevents_helper.rb
# Leeres CareventsHelper module
module CareventsHelper
end

app/views/carevents/_form.html.erb
<%= form_for(@carevent) do |f| %>
  <% if @carevent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carevent.errors.count, "error") %> verhindert/verhindern die Speicherung des Eintrags:</h2>

      <ul>
      <% @carevent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label 'Titel' %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label 'Beschreibung' %><br>
    <%= f.text_area :description %>
  </div>
    <div class="field">
      <%= f.label 'Kfz' %><br>
      <%= f.collection_select :car_id, Car.all, :id, :name %>
    </div>
  <div class="field">
    <%= f.label 'Start' %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label 'Ende' %><br>
    <%= f.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= f.submit value='Abschicken' %>
  </div>
<% end %>

app/views/carevents/edit.html.erb
<h1>Kfz-Nutzung editieren</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @carevent %> |
<%= link_to 'Zurück', carevents_path %>

app/views/carevents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kalender zur Kfz-Nutzung</h1>

<div id="button1"><h2><%= link_to 'Neue Kfz-Nutzung', new_carevent_path %></h2></div>

<br>
<br>

<%= month_calendar events: @carevents do |date, carevents| %>
    <b><%= date.strftime("%d.%m.%Y") %></b>

    <% carevents.each do |carevent| %>
        <div>
          <%= carevent.user.first_name %> <%= carevent.user.last_name %> - <%= link_to carevent.title, carevent %>
          <br>
          <%= carevent.car.name %>
          <br>
          <%= carevent.start_time.strftime("%H:%M") %> - <%= carevent.end_time.strftime("%H:%M") %>
          <br>
          <%= link_to 'A', carevent %> - <%= link_to 'E', edit_carevent_path(carevent) %> - <%= link_to 'L', carevent, method: :delete, data: { confirm: 'Sind Sie sicher?' } %>
          <hr>
        </div>
    <% end %>
<% end %>
<p>
Legende:<br>A -> Anzeigen, E -> Editieren, L -> Löschen
</p>

<h2>Insgesamt verfügbare Kraftfahrzeuge</h2>

<% @cars.each do |car| %>
<ul>
  <li><%= car.name %></li>
</ul>

<% end %>

app/views/carevents/new.html.erb
<h1>Neue Kfz-Nutzung</h1>

<%= render 'form' %>

<%= link_to 'Zurück', carevents_path %>

app/views/carevents/show.html.erb
<p>
  <strong>Mitarbeiter:</strong>
  <%= @carevent.user.first_name %> <%= @carevent.user.last_name %>
</p>

<p>
  <strong>Titel:</strong>
  <%= @carevent.title %>
</p>

<p>
  <strong>Beschreibung:</strong>
  <%= @carevent.description %>
</p>

<p>
  <strong>Kfz:</strong>
  <%= @carevent.car.name %>
</p>

<p>
  <strong>Start:</strong>
  <%= @carevent.start_time.strftime("%d.%m.%Y %H:%M") %>
</p>

<p>
  <strong>Ende:</strong>
  <%= @carevent.end_time.strftime("%d.%m.%Y %H:%M") %>
</p>


<%= link_to 'Editieren', edit_carevent_path(@carevent) %> |
<%= link_to 'Zurück', carevents_path %>