config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'

  get 'messages/index'

  get 'messages/new'

  ActiveAdmin.routes(self)
  resources :vacationplans
  resources :roomplans
  resources :carevents
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]
  # root 'welcome#index'

  get 'index' => 'welcome#index'
  get 'carevents/:id' => 'carevents#index'
  get 'roomplans/:id' => 'roomplans#index'
  get 'vacationplans/:id' => 'vacationplans#index'

  resources :messages do
    resources :comments
  end

  # root 'messages#index'
  # get 'welcome/index'

  # The priority is based upon order
  # of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller
  # actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webko</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand"<%= link_to 'Startseite' , index_path %></a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <%if user_signed_in? %>
            <li>
              <%= link_to 'Schwarzes Brett', messages_index_path %>
            </li>
            <li>
              <%= link_to 'Kfz-Nutzung', carevents_path %>
            </li>
            <li>
              <%= link_to 'Urlaubsplan', vacationplans_path %>
            </li>
            <li>
              <%= link_to 'Raumbelegung', roomplans_path %>
            </li>
            <li>
            <li>
              <a href ="">Eingeloggt als:  <strong><%= current_user.first_name %> <%= current_user.last_name %></strong></a>
            </li>
            <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
            </li>
          <% else %>
            <li>
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
            </li>
            <%end %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<!-- Page Content -->
<div class="container">

  <div class="row">
    <div class="col-lg-12 text-center">
      <%= yield %>
    </div>
  </div>
  <!-- /.row -->

</div>

<style>body{padding-top: 70px;}</style>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


</body>
</html>